import { ageDays } from "./utils.js";

const STORAGE_KEY = "skill-dashboard-usage";

/* ---------------------------------------------------------------------------
 * Real usage (generated by scripts/scan-usage.mjs from Codex session logs).
 * "sessions" = distinct Codex sessions the skill was invoked in — the honest
 * signal. localStorage views below only track dashboard inspections.
 * ------------------------------------------------------------------------- */

/**
 * Heat (0..1) drives the plasma visual: frequency on a log scale blended
 * with recency decay (~45-day scale). Zero sessions = stone cold.
 */
export function computeHeat(sessions, lastInvokedAt) {
  if (!sessions) return 0;
  const frequency = Math.min(1, Math.log2(1 + sessions) / 4.5);
  const recency = Math.exp(-ageDays(lastInvokedAt) / 45);
  return Math.min(1, frequency * 0.65 + recency * 0.35);
}

export function buildActivity(usagePayload, skills) {
  const map = new Map();
  for (const skill of skills) {
    const record = usagePayload?.usage?.[skill.id];
    const sessions = record?.sessions ?? 0;
    const reads = record?.reads ?? 0;
    const lastInvokedAt = record?.lastInvokedAt ?? null;
    const skillSizeTokens = skill.skillSizeTokens ?? 0;
    map.set(skill.id, {
      sessions,
      reads,
      lastInvokedAt,
      skillSizeTokens,
      estimatedFootprintTokens: skillSizeTokens * reads,
      heat: computeHeat(sessions, lastInvokedAt)
    });
  }
  return map;
}

const NO_ACTIVITY = {
  sessions: 0,
  reads: 0,
  lastInvokedAt: null,
  skillSizeTokens: 0,
  estimatedFootprintTokens: 0,
  heat: 0
};

export function getActivityFor(activity, skillId) {
  return activity?.get(skillId) ?? NO_ACTIVITY;
}

export function loadUsage() {
  if (typeof window === "undefined") return {};
  try {
    return JSON.parse(window.localStorage.getItem(STORAGE_KEY) ?? "{}");
  } catch {
    return {};
  }
}

export function saveUsage(usage) {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(STORAGE_KEY, JSON.stringify(usage));
}

export function getUsageForSkill(usage, skillId) {
  return usage[skillId] ?? { views: 0, lastViewedAt: null, pinned: false };
}

/**
 * Records an explicit inspection of a skill. Only deliberate selections should
 * call this — automatic fallback selections (filters removing the current
 * skill) would otherwise inflate view counts and silently hollow out the
 * Forgotten lens and the Unseen metric.
 */
export function markViewed(usage, skillId) {
  const current = getUsageForSkill(usage, skillId);
  const next = {
    ...usage,
    [skillId]: {
      ...current,
      views: current.views + 1,
      lastViewedAt: new Date().toISOString()
    }
  };
  saveUsage(next);
  return next;
}
